### ISSUE TITLE
Bug: structuredClone is not defined

### ISSUE THREAD

**Issue by FossilFrank** [FuelLabs/fuels-ts#1161]
### What version of fuels-ts are you using?

0.49.1

### Steps to Reproduce

I'm running a simple script:

```typescript
import { Provider } from "fuels";
import { RegistryContractAbi__factory } from "./contracts";

(async function() {
  const provider = new Provider('http://127.0.0.1:4000/graphql');

  const registry = RegistryContractAbi__factory.connect(String(process.env.REACT_APP_REGISTRY_CONTRACT_ID), provider);

  const vault = await registry.functions.vault().get();
  console.log({ vault });
})();
```

### Expected Behavior

Call the function

### Actual Behavior

```
node_modules/@fuel-ts/abi-coder/dist/index.js:677
        o[typeParameter] = structuredClone(arg.typeArguments?.[typeParameterIndex]);
          ^

ReferenceError: structuredClone is not defined
    at <anonymous> (node_modules/@fuel-ts/abi-coder/dist/index.js:677:11)
    at Array.reduce (<anonymous>)
    at Function.resolveGenericComponents (node_modules/@fuel-ts/abi-coder/dist/index.js:674:62)
    at Function.getArgSignatureContent (node_modules/@fuel-ts/abi-coder/dist/index.js:834:27)
    at Function.getArgSignature (node_modules/@fuel-ts/abi-coder/dist/index.js:806:26)
    at Function.getArgSignatureContent (node_modules/@fuel-ts/abi-coder/dist/index.js:837:23)
    at Function.getArgSignature (node_modules/@fuel-ts/abi-coder/dist/index.js:806:26)
    at <anonymous> (node_modules/@fuel-ts/abi-coder/dist/index.js:840:66)
    at Array.map (<anonymous>)
    at Function.getArgSignatureContent (node_modules/@fuel-ts/abi-coder/dist/index.js:840:48
```

**Comment by arboleya** [comment]
cc @nedsalk

**Comment by rtomas** [comment]
same problem here with a very single app in next.js

**Comment by arboleya** [comment]
@FossilFrank @rtomas It seems you are using NodeJS < 17, is that right? ([docs](https://nodejs.dev/en/api/v18/globals/#structuredclonevalue-options))

Could you please try again with a [newer version](https://github.com/FuelLabs/fuels-ts/blob/b3d6d529eb3f4acc23de6f8d73b7cad67c0dac98/package.json#L8) and report back?

**Comment by FossilFrank** [comment]
Correct, I'm using Node 16, I'll try updating it later

**Comment by nedsalk** [comment]
Given that v16 has reached [EOL](https://nodejs.org/en/blog/announcements/nodejs16-eol), this issue has become obsolete, as we plan on officially supporting only the latest two LTS versions, per internal discussions. Support for v20 is tracked in #1104, and v18 is used by the repo.
