### ISSUE TITLE
Possibly new Flaky test

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1234]
It's the second time I've seen this one:
- https://github.com/FuelLabs/fuels-ts/actions/runs/6054637504/job/16432359494?pr=1228#step:11:2180

Re-running the flow [fixed](https://github.com/FuelLabs/fuels-ts/actions/runs/6054637504/job/16432764096?pr=1228) it.

<details>
  <summary>Error output</summary>
  
```
Auth Testing › can check_msg_sender [with incorrect id]

    Invalid b256 (argument="b256", value="0xff0c90cc544d3fd7adfebd80196fa4157f8a0189967223ffb3e6eb01f37bc05:", code=INVALID_ARGUMENT, version=0.55.0)

      47 |
      48 |   throwError(message: string, value: unknown): never {
    > 49 |     return logger.throwArgumentError(message, this.name, value);
         |                   ^
      50 |   }
      51 |
      52 |   abstract encode(value: TInput, length?: number): Uint8Array;

      at Logger.makeError (node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at Logger.throwArgumentError (node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
      at B256Coder.throwError (packages/abi-coder/src/coders/abstract-coder.ts:49:19)
      at B256Coder.encode (packages/abi-coder/src/coders/b256.ts:16:12)
      at packages/abi-coder/src/coders/struct.ts:38:34
          at Array.map (<anonymous>)
      at StructCoder.encode (packages/abi-coder/src/coders/struct.ts:32:52)
      at packages/abi-coder/src/coders/tuple.ts:30:70
          at Array.map (<anonymous>)
      at TupleCoder.encode (packages/abi-coder/src/coders/tuple.ts:30:46)
      at FunctionFragment.encodeArguments (packages/abi-coder/src/function-fragment.ts:117:54)
      at createContractCall (packages/program/src/functions/base-invocation-scope.ts:29:21)
      at packages/program/src/functions/base-invocation-scope.ts:77:7
          at Array.map (<anonymous>)
      at FunctionInvocationScope.get calls [as calls] (packages/program/src/functions/base-invocation-scope.ts:76:42)
      at FunctionInvocationScope.updateScriptRequest (packages/program/src/functions/base-invocation-scope.ts:88:24)
      at FunctionInvocationScope.addCalls (packages/program/src/functions/base-invocation-scope.ts:152:10)
      at FunctionInvocationScope.addCall (packages/program/src/functions/base-invocation-scope.ts:140:10)
      at new FunctionInvocationScope (packages/program/src/functions/invocation-scope.ts:38:11)
      at Object.<anonymous> (packages/program/src/contract.ts:94:41)
      at Object.<anonymous> (packages/fuel-gauge/src/auth-testing.test.ts:50:10)
```
</details>

**Comment by arboleya** [comment]
I couldn't look into this yet, but here's another occurrence:
 - https://github.com/FuelLabs/fuels-ts/actions/runs/6076749870/job/16485259275#step:11:2184

```
value="0x054e0cc3d1e459631bd5f9ba1ce532b3f4a955a392824ad48694a83e5f25bd6:", 
```
