### ISSUE TITLE
The script call result does not contain a 'returnReceipt' on v0.71.1

### ISSUE THREAD

**Issue by drejohnson** [FuelLabs/fuels-ts#1663]
### What version of fuels-ts are you using?

0.71.1

### Steps to Reproduce

Follow the the quickstart guide for frontend but install latest version of ```fuels```

### Expected Behavior

Run the frontend without ```The script call result does not contain a 'returnReceipt'.``` error to be able to interact with the contract.

### Actual Behavior

Running the frontend from quickstart guide throw error on v0.71.1. Only versions up to v0.69.1 works without error:
```
ERROR
The script call result does not contain a 'returnReceipt'.

Receipts:
[
  {
    "type": "Panic",
    "id": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "reason": "0x2724028a0000000",
    "pc": "0x2868",
    "is": "0x2868",
    "contractId": "0x0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "type": "ScriptResult",
    "result": "0x2",
    "gasUsed": "0x0"
  }
]
Error: The script call result does not contain a 'returnReceipt'.

Receipts:
[
  {
    "type": "Panic",
    "id": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "reason": "0x2724028a0000000",
    "pc": "0x2868",
    "is": "0x2868",
    "contractId": "0x0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "type": "ScriptResult",
    "result": "0x2",
    "gasUsed": "0x0"
  }
]
    at decodeCallResult (http://localhost:3000/static/js/bundle.js:61269:11)
    at decodeContractCallScriptResult (http://localhost:3000/static/js/bundle.js:61452:95)
    at InvocationCallResult.getDecodedValue (http://localhost:3000/static/js/bundle.js:61581:28)
    at new InvocationResult (http://localhost:3000/static/js/bundle.js:61555:23)
    at new InvocationCallResult (http://localhost:3000/static/js/bundle.js:61655:5)
    at InvocationCallResult.build (http://localhost:3000/static/js/bundle.js:61667:28)
    at FunctionInvocationScope.dryRun (http://localhost:3000/static/js/bundle.js:61936:47)
    at async getCount (http://localhost:3000/static/js/bundle.js:76:11)
```

**Comment by arboleya** [comment]
You may have a version mismatch of some sort.

Please try using the [suggested](https://docs.fuel.network/docs/intro/quickstart-frontend/#installing) `0.60.0` version and let me know how it goes.

**Comment by nedsalk** [comment]
Which network are you trying to connect to? Beta-4? Beta-4 is supported until v0.69.1, whereas everything above is targeting the upcoming beta-5 network.

**Comment by drejohnson** [comment]
Yes, I'm connecting to Beta-4. Thanks, that clears it up!
