### ISSUE TITLE
Remove `fuel-ui` dependencies from templates

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1757]
Running `pnpm create fuels`, `pnpm fuels:dev` and then `pnpm dev` results in the following error:
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at generateClasses (file:///node_modules/.pnpm/@fuel-ui+react@0.21.1_@types+react-dom@18.2.19_@types+react@18.2.55_csstype@3.1.3/node_modules/@fuel-ui/react/dist/index.mjs:195:19)
    at file:///node_modules/.pnpm/@fuel-ui+react@0.21.1_@types+react-dom@18.2.19_@types+react@18.2.55_csstype@3.1.3/node_modules/@fuel-ui/react/dist/index.mjs:206:24
    at Object.useMemo (/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at useMemo (/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.development.js:1650:21)
    at useStyles (file:///node_modules/.pnpm/@fuel-ui+react@0.21.1_@types+react-dom@18.2.19_@types+react@18.2.55_csstype@3.1.3/node_modules/@fuel-ui/react/dist/index.mjs:206:10)
    at useFlexProps (file:///node_modules/.pnpm/@fuel-ui+react@0.21.1_@types+react-dom@18.2.19_@types+react@18.2.55_csstype@3.1.3/node_modules/@fuel-ui/react/dist/index.mjs:477:10)
    at file:///node_modules/.pnpm/@fuel-ui+react@0.21.1_@types+react-dom@18.2.19_@types+react@18.2.55_csstype@3.1.3/node_modules/@fuel-ui/react/dist/index.mjs:1221:21
    at file:///node_modules/.pnpm/@fuel-ui+react@0.21.1_@types+react-dom@18.2.19_@types+react@18.2.55_csstype@3.1.3/node_modules/@fuel-ui/react/dist/index.mjs:290:16
    at renderWithHooks (/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5842:18)
    at renderElement (/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
```

@luizstacio suggested that we remove the `fuel-ui` dependencies from our templates because the [`fuel-ui` repo](https://github.com/FuelLabs/fuel-ui) is not being actively maintained anymore.

**Comment by Dhaiwat10** [comment]
@fuel-ui has already been removed with this PR: https://github.com/FuelLabs/fuels-ts/pull/1691, just not released yet
