### ISSUE TITLE
Custom revert errors not showing w/ TypeScript SDK

### ISSUE THREAD

**Issue by theausicist** [FuelLabs/fuels-ts#1836]
### What version of fuels-ts are you using?

0.76.0

### Steps to Reproduce

use the following contract:

```sway
contract;
  
abi Tester {
    fn fail_implicity();
}

enum Error {
    FailImplicitly: ()
}

impl Tester for Contract {
    fn fail_implicity() {
        require(false, Error::FailImplicitly);
    }
}
 
```

using the Typescript SDK to deploy the contract (via local node) and execute:
```typescript
await tester.functions.fail_implicitly().call()
```

results in the following error:
```bash
     RequireRevertError: The script reverted with reason RequireFailed
      at revertErrorFactory (node_modules/@fuel-ts/program/src/revert/revert-error.ts:178:10)
      at RevertErrorCodes.getError (node_modules/@fuel-ts/program/src/errors.ts:7:7)
      at RevertErrorCodes.assert (node_modules/@fuel-ts/program/src/revert/revert-error-codes.ts:30:30)
      at new ScriptResultDecoderError (node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:15:30)
      at decodeCallResult (node_modules/@fuel-ts/program/src/script-request.ts:162:7)
      at decodeContractCallScriptResult (node_modules/@fuel-ts/program/src/contract-call-script.ts:219:7)
      at FunctionInvocationResult.getDecodedValue (node_modules/@fuel-ts/program/src/functions/invocation-results.ts:146:5)
      at new InvocationResult (node_modules/@fuel-ts/program/src/functions/invocation-results.ts:100:3)
      at new FunctionInvocationResult (node_modules/@fuel-ts/program/src/functions/invocation-results.ts:208:3)
      at Function.build (node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:39:10)
```

### Expected Behavior

Fail with proper reason: `FailImplicitly`. Imo, something like the following:

```bash
RequireRevertError: The script reverted: RequireFailed (reason: "FailImplicitly")
```

### Actual Behavior

Motivation (and related to): https://forum.fuel.network/t/custom-revert-errors-not-showing-w-typescript-sdk/4416/5

**Comment by theausicist** [comment]
this is mostly likely related to: https://github.com/FuelLabs/fuels-ts/issues/823

**Comment by theausicist** [comment]
this is related to: https://github.com/FuelLabs/fuels-ts/issues/823
