### ISSUE TITLE
setConfigurableConstants Error

### ISSUE THREAD

**Issue by cherideal** [FuelLabs/fuels-ts#2440]
### What version of fuels-ts are you using?

0.89.1

### Steps to Reproduce

  "configurables": [
    {
      "name": "MAX_SUPPLY",
      "configurableType": {
        "name": "",
        "type": 20,
        "typeArguments": null
      },
      "offset": 38352
    }
  ] --- configurables in abi

const configurableConstants = {
        MAX_SUPPLY: maxSupply,
    };
    const factory = new ContractFactory(bytecode, NativeAssetContractAbi__factory.abi, wallet)
    factory.setConfigurableConstants(configurableConstants)

### Expected Behavior

no exception

### Actual Behavior

node_modules/@fuel-ts/contract/src/contract-factory.ts:197
      throw new FuelError(
            ^
_FuelError: Error setting configurable constants on contract: offset is out of bounds.
    at ContractFactory.setConfigurableConstants (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/node_modules/@fuel-ts/contract/src/contract-factory.ts:197:13)
    at /home/cherideal/work/ShareWin/fuel-swap/Play-Ground/src/index.ts:62:13
    at step (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/src/index.ts:33:23)
    at Object.next (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/src/index.ts:14:53)
    at /home/cherideal/work/ShareWin/fuel-swap/Play-Ground/src/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/src/index.ts:4:12)
    at deploy_token_contract (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/src/index.ts:53:72)
    at /home/cherideal/work/ShareWin/fuel-swap/Play-Ground/src/index.ts:83:11
    at step (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/src/index.ts:33:23) {
  VERSIONS: { FORC: '0.60.0', FUEL_CORE: '0.27.0', FUELS: '0.89.1' },
  metadata: {},
  code: 'invalid-configurable-constants'
}

**Comment by arboleya** [comment]
@danielbate Could it be something related to encoding?

**Comment by danielbate** [comment]
Hmm it is likely a mismatch between the ABI and the bytecode being called, @cherideal could you share more info please such as the `forc` and `fuel-core` version you are using. An emaple repo would be really helpful.

**Comment by cherideal** [comment]
[toolchain]
channel = "nightly-2024-05-28"

[components]
forc = "0.60.0+nightly.20240528.4fe6f1ed51"
fuel-core = "0.26.0"

cherideal@ubuntu:~$ forc --version
forc 0.60.0+nightly.20240604.0e567287b4
cherideal@ubuntu:~$ fuel-core --version
fuel-core 0.27.0+nightly.20240604.0463dfd8bb
cherideal@ubuntu:~$ npm fules --version
10.7.0

**Comment by danielbate** [comment]
Would it be possible to get a minimal repo example containing the built ABI and bytecode?

**Comment by cherideal** [comment]
https://github.com/bookswapxyz/fuel-swap/tree/main
I have change forc/fuel-core version and work fine now, you need change the version back.

**Comment by danielbate** [comment]
Okay, good yes any mismatch in the `forc` version will mean a mismatch in the deployed bytecode vs the offsets in the ABI. Please could you close the issue if this is fixed.
