### ISSUE TITLE
New flaky test: Transaction id was already used

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#934]
I've seen this a couple of times now:
 - https://github.com/FuelLabs/fuels-ts/actions/runs/4792432893/jobs/8523938540?pr=924#step:11:1322

```
FAIL packages/example-contract/src/example-contract.test.ts
  ● ExampleContract › should return the input

    Transaction id was already used: 0xeab9f726ba65507def084bc3bdd9107c32ea6793f602c3411975f175eee5b5f8: {"response":{"data":null,"errors":[{"message":"Transaction id was already used: 0xeab9f726ba65507def084bc3bdd9107c32ea6793f602c3411975f175eee5b5f8","locations":[{"line":2,"column":3}],"path":["dryRun"]}],"status":200,"headers":{}},"request":{"query":"mutation dryRun($encodedTransaction: HexString!, $utxoValidation: Boolean) {\n  dryRun(tx: $encodedTransaction, utxoValidation: $utxoValidation) {\n    ...receiptFragment\n  }\n}\n\nfragment receiptFragment on Receipt {\n  data\n  rawPayload\n}","variables":{"encodedTransaction":"0x000000000000000000000000000000000000000005f5e1000000000000000000000000000000000400000000000000000000000000000001000000000000000200000000000000010000000000000000000000000000000000000000000000000000000000000000240000000000000000000000000000006b00bb793fec81293cbe8d9d6f180e0ef9a5a87e5e2d47a68394cb7e82ebeaeb000000000000000009c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58dbffffffffbaf3c2010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000309c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003371ceecdb6f9b8c308ef075845defc4eec5c2056d89aec6d26ad00f47e6564400000000000003e800000000000000000000000000000000000000000000000000000000000000000000000000000040eddac5913738e59f33196df00d3138d480ae28cf740d4e31754e348fb1c673b5ba3cc75ac6eda99f7ba9c1df9e495c034ec91541f4bc6ef869519cc8201dc41d","utxoValidation":false}}}

      at node_modules/.pnpm/graphql-request@5.0.0_graphql@16.6.0/node_modules/graphql-request/src/index.ts:497:11
      at step (node_modules/.pnpm/graphql-request@5.0.0_graphql@16.6.0/node_modules/graphql-request/dist/index.js:63:23)
      at Object.next (node_modules/.pnpm/graphql-request@5.0.0_graphql@16.6.0/node_modules/graphql-request/dist/index.js:44:53)
      at fulfilled (node_modules/.pnpm/graphql-request@5.0.0_graphql@16.6.0/node_modules/graphql-request/dist/index.js:35:58)
```

**Comment by arboleya** [comment]
Again here:
 - https://github.com/FuelLabs/fuels-ts/actions/runs/4861314612/jobs/8666211040?pr=950#step:11:1353

**Comment by arboleya** [comment]
https://github.com/FuelLabs/fuels-ts/actions/runs/4881166509/jobs/8709728837?pr=977#step:11:1285

**Comment by arboleya** [comment]
It looks like this has been fixed at some point.
