### ISSUE TITLE
[Question] Support for the new way of storage - when?

### ISSUE THREAD

**Issue by Lukasz2891** [FuelLabs/fuels-ts#982]
```
The script reverted with reason Unknown
RevertError: The script reverted with reason Unknown
    at revertErrorFactory (....node_modules/@fuel-ts/program/src/revert/revert-error.ts:95:14)
    at M.getError (....node_modules/@fuel-ts/program/src/revert/revert-error-codes.ts:43:12)
    at M.assert (....node_modules/@fuel-ts/program/src/revert/revert-error-codes.ts:24:30)
    at new E (....node_modules/@fuel-ts/program/src/errors.ts:24:43)
    at decodeCallResult (....node_modules/@fuel-ts/program/src/script-request.ts:94:11)
    at v.decodeCallResult (....node_modules/@fuel-ts/program/src/script-request.ts:189:12)
    at C.getDecodedValue (....node_modules/@fuel-ts/program/src/functions/invocation-results.ts:60:47)
    at new I (....node_modules/@fuel-ts/program/src/functions/invocation-results.ts:41:23)
    at new C (....node_modules/@fuel-ts/program/src/functions/invocation-results.ts:130:5)
    at Function.build (....node_modules/@fuel-ts/program/src/functions/invocation-results.ts:139:28)
    at x.dryRun (....node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:259:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
...
```

I got the issue when a new storage is used in the contract (sway `0.38.0`).

for example for a simple contract, just doing as follows:

```rust
    #[storage(read)]
    fn read_timestamp() -> u64 {
        storage.timestamp.read()
    }
```

When it will be possible to use that kind of contracts in the fuels-ts? 
I have the version `0.41.0`

**Comment by Dhaiwat10** [comment]
Hi, this should be supported shortly once we merge #986

**Comment by luizstacio** [comment]
@Lukasz2891 this is due to the new implementation on sway, you need to check if the value exists before read it.
`storage.timestamp.try_read().unwrap_or(0)`. We also had to fix on our examples https://github.com/FuelLabs/fuels-ts/blob/2ed283cdf93ea2c3a4c9ccc6e575fae30607a392/apps/docs-snippets/projects/counter/src/main.sw#L18

**Comment by Lukasz2891** [comment]
Thx, that seems to be the reason.
